checks:
  javascript: true

filter:
  paths:
    - 'src/*'
  dependency_paths:
    - 'node_modules/*'

build:
  environment:
      node: 16.14.2
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
