checks:
  javascript: true

filter:
  paths:
    - 'src/*'
  dependency_paths:
    - 'node_modules/*'

build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
      environment:
        node:
          version: 16.14.2
