name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: bedita-sdk
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      BEDITA_API_KEY: 1234567890
      BEDITA_API: http://localhost:8090
      BEDITA_ADMIN_USR: admin
      BEDITA_ADMIN_PWD: admin
      BEDITA_DOCKER_IMG: bedita/bedita:4.7.0
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'

      - name: 'Docker pull bedita image'
        run: 'docker pull ${BEDITA_DOCKER_IMG}'

      - name: 'Docker inspect bedita image'
        run: 'docker inspect ${BEDITA_DOCKER_IMG}'

      - name: 'Docker run bedita image'
        run: 'docker run --name api -d -p 8090:80 --env BEDITA_API_KEY=${BEDITA_API_KEY} --env BEDITA_ADMIN_USR=${BEDITA_ADMIN_USR} --env BEDITA_ADMIN_PWD=${BEDITA_ADMIN_PWD} ${BEDITA_DOCKER_IMG}'

      - name: 'Wait for 10'
        run: 'sleep 10'

      - name: 'Docker ps - show all containers'
        run: 'docker ps -a'

      - name: Install dependencies
        run: yarn install

      - name: Linter
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Coverage
        run: yarn coverage

      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: '65'
          filename: './coverage/clover.xml'

      - name: 'Export coverage results'
        uses: 'codecov/codecov-action@v1'
        with:
          file: './coverage/clover.xml'
          env_vars: NODE_VERSION

      - name: 'Archive code coverage results'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'NODE ${{ matrix.node-version }}'
          path: './coverage/clover.xml'

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - uses: actions/download-artifact@v2
        with:
          name: bedita-sdk
          path: dist

      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
